### ISSUE TITLE
Move trends rake task to dynflow action.

### ISSUE THREAD

**Issue by ezr-ondrej** [theforeman/foreman_statistics#11]
Currently installer installs a cron job, that is not adjustable and is created by foreman package. Instead of adding cron job for this plugin, we can move this to dynflow action

**Comment by ekohl** [comment]
Technically this now lives in 3 places: [RPM](https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/foreman/foreman/foreman.cron.d) / [Ubuntu Bionic](https://github.com/theforeman/foreman-packaging/blob/deb/develop/debian/bionic/foreman/foreman.cron.d) / [Debian Buster](https://github.com/theforeman/foreman-packaging/blob/deb/develop/debian/buster/foreman/foreman.cron.d). The installer doesn't touch this at all.

**Comment by ezr-ondrej** [comment]
[RM#9441](https://projects.theforeman.org/issues/9441)
